version: '1.0'
name: branch-pipeline1
displayName: BranchPipeline1
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: 11
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean install -Dmaven.test.skip=true
        artifacts:
          - name: qqbot_build
            path:
              - ./target
        caches:
          - null
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: qqbot_build
        artifactName: qqbot
        strategy: {}
        dependsOn: build_maven
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: qqbot
        version: 1.0.0
        autoIncrement: true
        strategy: {}
  - name: deploy-64786c8a
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: gz
        deployArtifact:
          - source: artifact
            name: qqbot
            target: ~/bot/
            artifactRepository: default
            artifactName: qqbot
            artifactVersion: latest
        script:
          - '# 请在此输入部署脚本，如启动Java应用如下'
          - '# nohup java -jar test.jar > nohup.out &'
          - cd ~/bot/
          - ls
          - tar -zxf qqbot.tar.gz
          - cd target
          - screen -R qqbot
          - java -jar qqbot-2.0.jar
          - echo "Deploy Success"
        notify: []
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
