version: '1.0'
name: dev_build
displayName: dev_build
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - dev
stages:
  - name: stage-3e79fde3
    displayName: Maven构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '11'
        mavenVersion: 3.3.9
        commands:
          - mvn -B clean install -Dmaven.test.skip=true
        artifacts:
          - name: qqbot
            path:
              - ./target
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
          expression: []
  - name: stage-475badbf
    displayName: 部署
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: rolling@agent
        name: rolling_deploy
        displayName: 主机滚动部署
        hostGroupID: gz
        rollingNum: 1/2
        deployArtifact:
          - source: build
            name: qqbot
            target: ~/bot/
            dependArtifact: qqbot
        script:
          - cd ~/bot/
          - java -jar qqbot.jar
        notify: []
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
